---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicetest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservicetest
    spec:
      containers:
      - name: microservicetest
        image: myuser/microservicetest:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: microservicetest
---
apiVersion: v1
kind: Service
metadata:
  name: microservicetest
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: microservicetest
